#!/usr/bin/env bash
# vim: set ft=ruby:

# bash/ruby hack extracted from selecta script.
#   link: https://github.com/garybernhardt/selecta

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

# Modified version of the original hook from BigBinary:
# - link: http://blog.bigbinary.com/2013/09/19/do-not-allow-force-pusht-to-master.html

class StopForce

  BLACKLIST = %w[master production]

  def call
    reject if pushing_to_blacklisted? && forced_push?
  end

  def pushing_to_blacklisted?
    blacklist = ENV['GIT_HOOKS_BLACKLIST'] || BLACKLIST
    blacklist.include? current_branch
  end

  def current_branch
    @current_branch ||= `git rev-parse --abbrev-ref HEAD`.strip
  end

  def forced_push?
    input = $stdin.gets

    if input.nil? || input.empty?
      false
    else
      # The pre-push hook receives info about
      # The commits in this format:
      #
      #     <local ref> SP <local sha1> SP <remote ref> SP <remote sha1> LF
      #
      # The function to check if is a force push
      # is extracted from the git-scm.com website:
      # - link: http://git-scm.com/book/en/Customizing-Git-An-Example-Git-Enforced-Policy
      #
      # We see if any commits are reachable from the older revision that
      # aren’t reachable from the newer one.
      # If there are none, then it was a fast-forward push;
      # otherwise, we deny it
      _, newrev, _, oldrev = input.split(' ')
      missed_refs = `git rev-list #{newrev}..#{oldrev}`
      missed_ref_count = missed_refs.split("\n").size
      missed_ref_count > 0
    end
  end

  def reject
    messages = ["Your attempt to FORCE PUSH to #{current_branch.upcase} has been rejected."]
    messages << "If you still want to FORCE PUSH then you need to ignore the pre_push git hook by executing following command."
    messages << "    $ git push origin #{current_branch} --force --no-verify"
    feedback messages

    exit 1
  end

  def feedback(messages)
    sep = "*" * 40
    $stdout.puts sep
    Array(messages).each { |message| $stdout.puts message }
    $stdout.puts sep
  end
end

StopForce.new.call
