#!/usr/bin/env ruby

require File.expand_path("hook", File.dirname(__FILE__))

# Call #run_hooks with the name of the scripts that will be
# executed when this hook is called. Add :& as the last argument
# to run the scripts in background. Each hook will run in order.
#
# All the scripts must be in the directory:
#
#     hooks/bin/
#
#
# Example:
#
#    # background scripts, they don't stop the execution
#    # of the git command
#    run_hooks "bundler", "ctags", :&
#    # you also can use the #detach_hooks method
#    detach_hooks "bundler", "ctags"
#
#    # normal hook
#    run_hook "no-commit"

run_hooks "ctags", :&
