#!/usr/bin/env bash
# vim: set ft=ruby:

# bash/ruby hack extracted from selecta script.
#   link: https://github.com/garybernhardt/selecta

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

require_relative 'hook'

Hook.new('pre-push', %w[stop-force]).call
